# This section declares settings for the database.
[database]

# The database for caching, support Redis only:
#   redis://<user>:<password>@<host>:<port>/<db_number>
cache_store = "redis://redis:6379"

# The database for persist data, support MySQL, Postgres, ClickHouse and MongoDB:
#   mysql://[username[:password]@][protocol[(address)]]/dbname[?param1=value1&...&paramN=valueN]
#   postgres://bob:secret@1.2.3.4:5432/mydb?sslmode=verify-full
#   clickhouse://user:password@host[:port]/database?param1=value1&...&paramN=valueN
#   mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[defaultauthdb][?options]]
data_store = "mysql://gorse:gorse_pass@tcp(mysql:3306)/gorse?parseTime=true"

# The cache size for recommended/popular/latest items. The default value is 100.
cache_size = 200

# Insert new users while inserting feedback. The default value is true.
auto_insert_user = true

# Insert new items while inserting feedback. The default value is true.
auto_insert_item = false

# The feedback types for positive events.
positive_feedback_types = ["star","like"]

# The feedback types for read events.
read_feedback_types = ["read"]

# The time-to-live (days) of positive feedback, 0 means disabled. The default value is 0.
positive_feedback_ttl = 0

# The time-to-live (days) of items, 0 means disabled. The default value is 0.
item_ttl = 0

# This section declares settings for the master node.
[master]
port = 8086                     # master port
host = "0.0.0.0"                # master host
http_port = 8088                # HTTP API port
http_host = "0.0.0.0"           # HTTP API host
n_jobs = 4                      # number of working jobs
meta_timeout = 10               # cluster meta timeout (second)

# This section declares settings for the server node.
[server]
default_n = 20                  # default number of returned items
api_key = "19260817"            # secret key for RESTful APIs (SSL required)

# This section declares settings for recommendation.
[recommend]

# The time window of popular items (days). The default values is 180.
popular_window = 365

# The time period for model fitting (minutes). The default values is 60.
fit_period = 10

# The time period for model searching (minutes). The default values is 100.
search_period = 60

# The number of epochs for model searching. The default values is 100.
search_epoch = 100

# The number of trials for model searching. The default values is 10.
search_trials = 10

# The time period to refresh recommendation for inactive users (days). The default values is 5.
refresh_recommend_period = 1

# The fallback recommendation method for cold-start users:
#   item_based: Recommend similar items to cold-start users.
#   popular: Recommend popular items to cold-start users.
#   latest: Recommend latest items to cold-start users.
# The default values is ["latest"].
fallback_recommend = ["item_based", "latest"]

# The number of latest (cold-start) items insert to recommended items cache. The default values is 10.
explore_latest_num = 20

# The type of neighbors for items. There are three types:
#   similar: Neighbors are found by number of common labels.
#   related: Neighbors are found by number of common users.
#   auto: If a item have labels, neighbors are found by number of common labels.
#         If this item have no labels, neighbors are found by number of common users.
# The default values is "auto".
item_neighbor_type = "similar"

# The type of neighbors for users. There are three types:
#   similar: Neighbors are found by number of common labels.
#   related: Neighbors are found by number of common liked items.
#   auto: If a user have labels, neighbors are found by number of common labels.
#         If this user have no labels, neighbors are found by number of common liked items.
# The default values is "auto".
user_neighbor_type = "similar"

# Enable latest recommendation during offline recommendation. The default values is false.
enable_latest_recommend = true

# Enable popular recommendation during offline recommendation. The default values is false.
enable_popular_recommend = false

# Enable user-based similarity recommendation during offline recommendation. The default values is false.
enable_user_based_recommend = true

# Enable item-based similarity recommendation during offline recommendation. The default values is false.
enable_item_based_recommend = false

# Enable collaborative filtering recommendation during offline recommendation. The default values is true.
enable_collaborative_recommend = true
