{
 "title": "Gorse Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "log datasource", "query": "loki" },
   { "name": "DS_PROMETHEUS", "label": "metrics datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(gorse_master_users_total, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Data Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_users_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_active_users_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Items",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_items_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Active Items",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_active_items_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "User Labels",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_user_labels_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Feedback",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_feedbacks_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Implicit Feedback",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_implicit_feedbacks_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Positive Feedback",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_positive_feedbacks_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Negative Feedback",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_negative_feedbacks_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Inactive Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_inactive_users_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Inactive Items",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_inactive_items_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Item Labels",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_item_labels_total{job=\"$job\"}"
    }
   ]
  },
  { "title": "Recommendation / System Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Collaborative Precision@10",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_collaborative_filtering_precision_10{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Collaborative Recall@10",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_collaborative_filtering_recall_10{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Collaborative NDCG@10",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_collaborative_filtering_ndcg_10{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Fatal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$job\",level=\"fatal\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Fatal / Error / Warning Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"$job\",level=~\"warn|error|fatal\"}"
    }
   ]
  },
  {
   "title": "Ranking Precision",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_ranking_model_precision{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Ranking Recall",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_ranking_model_recall{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Ranking AUC",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_ranking_model_auc{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$job\",level=\"error\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "User Neighbor Recall",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_user_neighbor_index_recall{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Item Neighbor Recall",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_master_item_neighbor_index_recall{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Collaborative Index Recall",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gorse_worker_collaborative_filtering_index_recall{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$job\",level=\"warn\"}[$__interval]))"
    }
   ]
  },
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(gorse_server_rest_api_request_seconds_bucket{job=\"$job\"}[$__interval]))",
     "legendFormat": "{{ api }}"
    }
   ]
  },
  {
   "title": "Slow Requests (Response Time > 100ms)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"$job\",level=~\"info\"}|json|response_time > 0.1"
    }
   ]
  },
  {
   "title": "Worker Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Refreshed Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "gorse_worker_update_user_recommend_total{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Recommend Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gorse_worker_offline_recommend_step_seconds{job=\"$job\"}",
       "legendFormat": "{{ step }}"
      },
      {
       "expr": "gorse_worker_offline_recommend_total_seconds{job=\"$job\"}",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Master Status: Load Dataset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Dataset Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "gorse_master_load_dataset_total_seconds{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Load Dataset Steps Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gorse_master_load_dataset_step_seconds{job=\"$job\"}",
       "legendFormat": "{{ step }}"
      },
      {
       "expr": "gorse_master_load_dataset_total_seconds{job=\"$job\"}",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Master Status: Find Item Neighbors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Refreshed Items",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "gorse_master_update_item_neighbors_total{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Find Item Neighbors Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gorse_master_find_item_neighbors_seconds{job=\"$job\"}",
       "legendFormat": "{{ step }}"
      },
      {
       "expr": "gorse_master_find_item_neighbors_total_seconds{job=\"$job\"}",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Master Status: Find User Neighbors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Refreshed Users",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "gorse_master_update_user_neighbors_total{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Find User Neighbors Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gorse_master_find_user_neighbors_seconds{job=\"$job\"}",
       "legendFormat": "{{ step }}"
      },
      {
       "expr": "gorse_master_find_user_neighbors_total_seconds{job=\"$job\"}",
       "legendFormat": "total"
      }
     ]
    }
   ]
  },
  {
   "title": "Master Status: Collaborative Filtering Model",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Precision@10",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "gorse_master_collaborative_filtering_precision_10{job=\"$job\"}",
       "legendFormat": "fit"
      },
      {
       "expr": "gorse_master_collaborative_filtering_search_precision_10{job=\"$job\"}",
       "legendFormat": "sarch"
      }
     ]
    },
    {
     "title": "Fit / Search Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gorse_master_collaborative_filtering_fit_seconds{job=\"$job\"}",
       "legendFormat": "fit"
      },
      {
       "expr": "gorse_master_collaborative_filtering_search_seconds{job=\"$job\"}",
       "legendFormat": "search"
      }
     ]
    }
   ]
  },
  {
   "title": "Master Status: Ranking Model",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Precision@10",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "gorse_master_ranking_model_precision{job=\"$job\"}",
       "legendFormat": "fit"
      },
      {
       "expr": "gorse_master_ranking_search_precision{job=\"$job\"}",
       "legendFormat": "sarch"
      }
     ]
    },
    {
     "title": "Fit / Search Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gorse_master_ranking_fit_seconds{job=\"$job\"}",
       "legendFormat": "fit"
      },
      {
       "expr": "gorse_master_ranking_search_seconds{job=\"$job\"}",
       "legendFormat": "search"
      }
     ]
    }
   ]
  },
  {
   "title": "Master Status: Cache Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scanned / Reclaimed Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "gorse_master_cache_scanned_total{job=\"$job\"}",
       "legendFormat": "scanned"
      },
      {
       "expr": "gorse_master_cache_reclaimed_total{job=\"$job\"}",
       "legendFormat": "reclaimed"
      }
     ]
    },
    {
     "title": "Garbage Collection Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gorse_master_cache_scanned_seconds{job=\"$job\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Allocated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=\"$job\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "CPU Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[$__interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Master Node Memory Inuse",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "gorse_master_memory_inuse_bytes{job=\"$job\"}",
       "legendFormat": "{{ data }}"
      }
     ]
    },
    {
     "title": "Worker Node Memory Inuse",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "gorse_worker_memory_inuse_bytes{job=\"$job\"}",
       "legendFormat": "{{ data }}"
      }
     ]
    }
   ]
  }
 ]
}