# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocol.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protocol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06labels\x18\x02 \x01(\x0c\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x12\x11\n\tsubscribe\x18\x04 \x03(\t\"\xa1\x01\n\x04Item\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x11\n\tis_hidden\x18\x03 \x01(\x08\x12\x12\n\ncategories\x18\x04 \x03(\t\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06labels\x18\x06 \x01(\x0c\x12\x0f\n\x07\x63omment\x18\x07 \x01(\t\"\xa5\x01\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x15\n\rfeedback_type\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0f\n\x07item_id\x18\x04 \x01(\t\x12\r\n\x05value\x18\x05 \x01(\x01\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x63omment\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=51
  _globals['_USER']._serialized_end=126
  _globals['_ITEM']._serialized_start=129
  _globals['_ITEM']._serialized_end=290
  _globals['_FEEDBACK']._serialized_start=293
  _globals['_FEEDBACK']._serialized_end=458
# @@protoc_insertion_point(module_scope)
