{
 "title": "Gorse Cache",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Get Scores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Get Scores Count (10 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(gorse_cache_get_scores_seconds_count{}[10m]))"
    }
   ]
  },
  {
   "title": "Get Scores Latency (Quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_cache_get_scores_seconds_bucket{}[10m])))"
    }
   ]
  },
  { "title": "Set Scores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Set Scores Count (10 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(gorse_cache_set_scores_seconds_count{}[10m]))"
    }
   ]
  },
  {
   "title": "Set Scores Latency (Quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_cache_set_scores_seconds_bucket{}[10m])))"
    }
   ]
  },
  {
   "title": "Append Scores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Append Scores Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(increase(gorse_cache_append_scores_seconds_count{}[10m]))"
      }
     ]
    },
    {
     "title": "Append Scores Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_cache_append_scores_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Clear Scores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clear Scores Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(gorse_cache_clear_scores_seconds_count{}[10m]))"
      }
     ]
    },
    {
     "title": "Clear Scores Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_cache_clear_scores_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  }
 ]
}