{
 "title": "Gorse Database",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Batch Insert Feedback", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Batch Insert Feedback Count (10 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "round(sum(increase(gorse_database_batch_insert_feedback_seconds_count{}[10m])))"
    }
   ]
  },
  {
   "title": "Batch Insert Feedback Latency (Quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_batch_insert_feedback_seconds_bucket{}[10m])))"
    }
   ]
  },
  { "title": "Batch Insert Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Batch Insert Users Count (10 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "round(sum(increase(gorse_database_batch_insert_users_seconds_count{}[10m])))"
    }
   ]
  },
  {
   "title": "Batch Insert Users Latency (Quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_batch_insert_users_seconds_bucket{}[10m])))"
    }
   ]
  },
  { "title": "Batch Insert Items", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Batch Insert Items Count (10 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "round(sum(increase(gorse_database_batch_insert_items_seconds_count{}[10m])))"
    }
   ]
  },
  {
   "title": "Batch Insert Items Latency (Quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_batch_insert_items_seconds_bucket{}[10m])))"
    }
   ]
  },
  {
   "title": "Get User Feedback",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get User Feedback Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "round(sum(increase(gorse_database_get_user_feedback_seconds_count{}[10m])))"
      }
     ]
    },
    {
     "title": "Get User Feedback Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_get_user_feedback_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Get Item Feedback",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get Item Feedback Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "round(sum(increase(gorse_database_get_item_feedback_seconds_count{}[10m])))"
      }
     ]
    },
    {
     "title": "Get Item Feedback Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_get_item_feedback_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Get User-Item Feedback",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get User-Item Feedback Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "round(sum(increase(gorse_database_get_user_item_feedback_seconds_count{}[10m])))"
      }
     ]
    },
    {
     "title": "Get User-Item Feedback Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_get_user_item_feedback_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Get User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get User Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "round(sum(increase(gorse_database_get_user_seconds_count{}[10m])))"
      }
     ]
    },
    {
     "title": "Get User Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_get_user_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Get Item",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get Item Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "round(sum(increase(gorse_database_get_item_seconds_count{}[10m])))"
      }
     ]
    },
    {
     "title": "Get Item Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_get_item_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Delete User-Item Feedback",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delete User-Item Feedback Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "round(sum(increase(gorse_database_delete_user_item_feedback_seconds_count{}[10m])))"
      }
     ]
    },
    {
     "title": "Delete User-Item Feedback Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_delete_user_item_feedback_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Delete User",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delete User Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "round(sum(increase(gorse_database_delete_user_seconds_count{}[10m])))"
      }
     ]
    },
    {
     "title": "Delete User Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_delete_user_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Delete Item",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Delete Item Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "round(sum(increase(gorse_database_delete_item_seconds_count{}[10m])))"
      }
     ]
    },
    {
     "title": "Delete Item Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_delete_item_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Get Click-through Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get Click-through Rate Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "round(sum(increase(gorse_database_get_click_through_rate_seconds_count{}[10m])))"
      }
     ]
    },
    {
     "title": "Get Click-through Rate Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_get_click_through_rate_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Insert Measurements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Insert Measurements Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "round(sum(increase(gorse_database_insert_measurement_seconds_count{}[10m])))"
      }
     ]
    },
    {
     "title": "Insert Measurements Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_database_insert_measurement_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  }
 ]
}