{
 "title": "Gorse Master",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Find User Neighbors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Find User Neighbors Count (10 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(gorse_master_find_user_neighbors_seconds_count{}[10m]))"
    }
   ]
  },
  {
   "title": "Find User Neighbors Latency (Quantile 99%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_master_find_user_neighbors_seconds_bucket{}[10m])))"
    }
   ]
  },
  { "title": "Find Item Neighbors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Find Item Neighbors Count (10 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(gorse_master_find_item_neighbors_seconds_count{}[10m]))"
    }
   ]
  },
  {
   "title": "Find Item Neighbors Latency (Quantile 99%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_master_find_item_neighbors_seconds_bucket{}[10m])))"
    }
   ]
  },
  {
   "title": "Send Click-through Rate Prediction Model",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Send Click-throgh Rate Prediction Model Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(increase(gorse_master_get_click_model_seconds_count{}[10m]))"
      }
     ]
    },
    {
     "title": "Send Click-through Rate Prediction Model Latency (Quantile 99%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_master_get_click_model_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Send Collaborative Filtering Model",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Send Collaborative Filtering Model Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(gorse_master_get_ranking_model_seconds_bucket{}[10m]))"
      }
     ]
    },
    {
     "title": "Send Collaborative Filtering Model Latency (Quantile 99%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_master_get_ranking_model_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Send User Index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Send User Index Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(gorse_master_get_user_index_seconds_count{}[10m]))"
      }
     ]
    },
    {
     "title": "Send User Index Latency (Quantile 99%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_master_get_user_index_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  }
 ]
}