{
 "title": "Gorse Worker",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Get Recommend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Get Recommend Count (10 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(gorse_worker_get_recommend_seconds_count{}[10m]))"
    }
   ]
  },
  {
   "title": "Get Recommend Latency (Quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_worker_get_recommend_seconds_bucket{}[10m])))"
    }
   ]
  },
  {
   "title": "Collaborative Filtering Recommend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  { "title": "Click-through Rate Prediction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Click-through Rate Prediction Count (10 Minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(gorse_worker_ctr_recommend_seconds_count{}[10m]))"
    }
   ]
  },
  {
   "title": "Click-through Rate Prediction Latency (Quantile 0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_worker_ctr_recommend_seconds_bucket{}[10m])))"
    }
   ]
  },
  {
   "title": "User-based Recommend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "User-based Recommend Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(gorse_worker_user_based_recommend_seconds_count{}[10m]))"
      }
     ]
    },
    {
     "title": "User-based Recommend Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_worker_user_based_recommend_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Item-based Recommend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Item-based Recommend Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(gorse_worker_item_based_recommend_seconds_count{}[10m]))"
      }
     ]
    },
    {
     "title": "Item-based Recommend Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_worker_item_based_recommend_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Latest Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Latest Items Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(gorse_worker_load_latest_recommend_cache_seconds_count{}[10m]))"
      }
     ]
    },
    {
     "title": "Load Latest Items Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_worker_load_latest_recommend_cache_seconds_bucket{}[10m])))"
      }
     ]
    },
    {
     "title": "Collaborative Filtering Recommend Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(increase(gorse_worker_collaborative_recommend_seconds_count{}[10m]))"
      }
     ]
    },
    {
     "title": "Collaborative Filtering Recommend Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_worker_collaborative_recommend_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Popular Items",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Popular Items Count (10 Minutes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(gorse_worker_load_popular_recommend_cache_seconds_count{}[10m]))"
      }
     ]
    },
    {
     "title": "Load Popular Items Latency (Quantile 0.99)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(le) (increase(gorse_worker_load_popular_recommend_cache_seconds_bucket{}[10m])))"
      }
     ]
    }
   ]
  }
 ]
}